app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'app'
urlpatterns = [
    path('',views.index,name='index'),
    path('mypage',views.mypage, name='mypage'),
    path('about',views.about,name='about'),
    path('createpost/',views.createpost, name='createpost'),
    path('bosyuu_detail<int:postcontent_id>/editpost/',views.editpost,name='bosyuu_edit'),
    path('bosyuu_detail<int:postcontent_id>/',views.bosyuu_detail, name='bosyuu_detail'),
    path('bosyuu_detail<int:postcontent_id>/delete/',views.bosyuu_delete,name='bosyuu_delete'),
    path('signup/', views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='app/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('',views.index, name='index'),
    path('<str:name1>_<str:name2>/', views.room, name='room'),
]

search/urls.py
from django.urls import path
from .import views
from django.views.decorators.cache import cache_page 


app_name = 'search'
urlpatterns = [
    path('',views.search,name='bosyuu_article')
]

app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<div class="about">
    <h2>このサイトについて</h2>
    <p>このサイトは、オオタカケンジ　による習作、ポートフォリオサイトです。</p>
    <h3>【利用方法】</h3>
    <ul>
        <li>1. ユーザー名とパスワードを設定して新規会員登録をしてください。</li>
        <li>2. メンバーを募集したい方は記事を書いてみましょう！マイページから新しく作ることができます！<br>
            (本サイトはオーディオファイルの添付が必須となっています。他人の曲や演奏を貼っちゃダメです。)</li>
        <li>3. 「さがす」メニューから、自分に合う条件の記事を検索してみましょう！</li>
        <li>4. 気になる記事が見つかったら、その投稿者とチャットでお話ししてみましょう！記事の詳細ページから、相手とのチャットルームに入れます。</li>
    </ul>

    <h3>【学習の目的】</h3>
    <ul>
        <li>・Djangoとpython、バックエンドの学習</li>
        <li>・MVCフレームワークの学習（Djangoは正式にはMVTですが）</li>
        <li>・Webサービスとして最低限、一通りの機能を有するアプリをゼロから自分で考え実装する経験を得る。</li>
        <li>・大手メン募サイトは音源を外部アプリへのリンクという形でしか聴けないので、<br>
            外部に飛ばずとも簡単に音を聴いてメンバーを探せるサービスがあったらいいのにと思っていたので作ってみた</li>
    </ul>
    
    <h3>【実装した機能】</h3>
    <ul>
        <li>・新規会員登録</li>
        <li>・ログイン、ログアウト機能</li>
        <li>・記事の新規作成、編集、削除</li>
        <li>・記事の一覧表示</li>
        <li>・記事の個別表示</li>
        <li>・記事の検索</li>
        <li>・他ユーザーとのLINE風リアルタイムチャット</li>
        <li>・やりとりしているユーザーの一覧表示</li>
        <li>・オーディオファイルのアップロード</li>
        <li>・簡易オーディオプレイヤー</li>
    </ul>

    <h3>【今後追加したい機能】</h3>
    <ul>
        <li>・ページネーション</li>
        <li>・コミュニティ機能</li>
        <li>・本格的なオーディオプレイヤー</li>
        <li>・OAuth認証</li>
    </ul>

    <h3>【このアプリで使用した技術・ツール等】</h3>
    <ul>
        <li>・Django</li>
        <li>・Python</li>
        <li>・Channels</li>
        <li>・Django-debug-toolbar</li>
        <li>・WebSocket</li>
        <li>・Heroku</li>
        <li>・Git</li>
        <li>・GitHub</li>
        <li>・Docker</li>
        <li>・Redis</li>
        <li>・AWS(S3)</li>
        <li>・Adobe XD</li>
        <li>・HTML5</li>
        <li>・CSS3</li>
        <li>・Javascript</li>
        <li>・jQuery</li>
        <li>・(memchached)</li>
        <li>↑表示速度改善のため一度は実装するも、<br>
            不可欠なリアルタイム性との兼ね合いを考えた結果、使用を中止。</li>
    </ul>

    <h3>【オオタカケンジの経験・スキルセット（上記以外）】</h3>
    <ul>
        <li>・PHP＋MySQL（スクラッチで簡易的な掲示板を作った程度です）</li>
        <li>・WordpressでのHP制作</li>
        <li>・Vue.js（jQueryの代替として、上記wpサイトに使用。ハンバーガーメニューやモーダルウィンドウを作った程度。）</li>
        <li>・Linux（CLI）＊業務経験</li>
        <li>・VMWare（ESXi）による仮想マシン構築　＊業務経験</li>
        <li>・オンプレでのサーバー構築（LAMP環境構築）＊業務経験</li>
        <li>・AWS（VPC,EC2）でのインフラ構築</li>
        <li>・Swift（簡単な単機能アプリを作った程度）</li>
        <li>・Adobe Illusrator</li>
        <li>・Adobe Photoshop *業務で基本機能を使用</li>
    </ul>
    
    <h3>【その他】</h3>
    <p>・勉強が趣味みたいなもの（プログラミングも、それ以外も）</p>
    <p>・新しい技術を積極的に身につけたいです。このアプリ作り終えたらブロックチェーンの勉強をしたいと思っています。</p>
    <p>・多趣味&そこそこ社会問題等への関心も高いので、それらとプログラミングを結び付けて、<br>
        社会の役に立つもの、自分と同じ趣味の人たちの役に立つもの、完全に自己満足なもの等、どんどん作ってみたいです</p>
</div>
{% endblock %}

app/templates/app/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>membo | オリジナル曲バンド専用のメンバー募集サイト</title>
</head>
<body>
    <div id="app" class="container-all">
        <header>
            <div class="header-contents-container">
                <div class="title-logo-container">
                    <a href="{% url 'app:index' %}">
                        <h1 class="title-logo">membo</h1>
                        <span class="title-logo-sub">オリジナル曲バンド専用のメンバー募集サイト</span>
                    </a>
                </div>
                <!-- <div class="header-menus-and-icon"> -->
                    <!-- <div class="ham-icon-container"> -->
                        <img class="hamburger" src="{% static 'images/hamburger.png' %}" alt="menuを表示" srcset="">
                    <!-- </div> -->
                    <nav class="header-menus">
                        <a href="{% url 'app:about' %}" class="header-menu-list-text">
                            このサイトについて
                        </a>
                        <a href="{% url 'search:bosyuu_article' %}" class="header-menu-list-text">
                            さがす
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:index' %}" class="header-menu-list-text">
                            チャット
                        </a>
                        <a href="{% url 'app:mypage' %}" class="header-menu-list-text">
                            マイページ
                        </a>
                        <a href="{% url 'app:logout' %}" class="header-menu-list-text">
                            ログアウト
                        </a>
                        {% else %}
                        <a href="{% url 'app:login' %}" class="header-menu-list-text">
                            ログイン
                        </a>
                        <a href="{% url 'app:signup' %}" class="header-menu-list-text">
                            新規会員登録
                        </a>
                        {% endif %}
                        </ul>
                    </nav>
                <!-- </div> -->
            </div>
        </header>
        <main class="main-container">
            <div class="main-container-contents">
                {% block content %}
                {% endblock %}
            </div>
            <div class="main-container-ad-sidebar-container">
                <div class="main-container-ad-sidebar">
                    広告欄
                </div>
            </div>
        </main>
        <footer>
            <small class="copyrights">
                    ©2020.otkken2
            </small>
        </footer>
    </div>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous">
    </script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
    <script src="{% static 'JS/main.js' %}"></script>
</body>
</html>

app/templates/app/bosyuu-article.html
{% load widget_tweaks %}
<form  method="POST" class="post-tabpanel-bosyuuform" enctype="multipart/form-data" >{% csrf_token %}
    <div class="fields form-title">
        <h3>{{ form.title.label }}</h3>
        {{ form.title|add_class:"post-form-title"}}                
    </div>
    <div class="fields form-sound">
        <h3>{{ form.sound.label }}</h3>
        {{ form.sound|add_class:"post-form-sound" }}
    </div>
    <div class="fields form-text">
        <h3>{{ form.text.label }}</h3>
        {{ form.text|add_class:"post-form-text" }}
    </div>
    <div class="fields form-active_area">
        <h3>{{ form.active_area.label }}</h3>
        {{ form.active_area|add_class:"post-form-active_area" }}
    </div>
    <div class="fields form-mypart">
        <h3>{{ form.mypart.label }}</h3>
        {{ form.mypart|add_class:"post-form-mypart" }}
    </div>
    <div class="fields form-recruite_part">
        <h3>{{ form.recruite_part.label }}</h3>
        {{ form.recruite_part|add_class:"post-form-recruite_part" }}
    </div>
    <div class="fields form-genre">
        <h3>{{ form.genre.label }}</h3>
        {{ form.genre|add_class:"post-form-genre" }}
    </div>
    <div class="fields form-favorite">
        <h3>{{ form.favorite.label }}</h3>
        {{ form.favorite|add_class:"post-form-favorite" }}
    </div>
    <div class="fields form-days_of_theweek">
        <h3>{{ form.days_of_theweek.label }}</h3>
        {{ form.days_of_theweek|add_class:"post-form-days_of_theweek" }}
    </div>
    <br>
    <div class="button-container">
        <button type="submit" class="btn-post-create">この内容で保存</button>
    </div>
</form>

app/templates/app/bosyuu_detail.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
    <ol class="breadcrumb"><!-- パンクズリスト -->
        <li><a href="{% url 'app:index' %}"><small>トップページ</small></a></li>
        <li><small>記事詳細</small></li>
    </ol>
    <h2>記事詳細</h2>
    <section class="post">

        <div class="post-header">
            <div class="post-title">    
                <h3>{{ postcontent.title }}</h3>
            </div>
            <div class="post-meta">
                （{{ postcontent.author }}/投稿日時：　{{ postcontent.post_date }}）
            </div>
        </div>

        <div class="post-contents">
            <div class="post-content-sound"><audio controls><source src="{{ postcontent.sound.url }}" type="audio/mp3" /></audio></div>
            
            <div class="post-content-issues">
                <ul>
                    <li>担当パート:
                        {% for mypart in postcontent.mypart.all %}
                        {{ mypart }},
                        {% endfor %}
                    </li>
                    <li>募集パート:
                        {% for recruite_part in postcontent.recruite_part.all %}
                        {{ recruite_part }},
                        {% endfor %}
                    </li>
                    <li>活動地域:
                        {% for active_area in postcontent.active_area.all %}
                        {{ active_area }},
                        {% endfor %}
                    </li>
                    <li>影響:{{ postcontent.favorite }}</li>
                    <li>ジャンル:
                        {% for genre in postcontent.genre.all %}
                        {{ genre }},
                        {% endfor %}
                    </li>
                    <li>
                        曜日:
                        {% for days_of_theweek in postcontent.days_of_theweek.all %}
                        {{ days_of_theweek }}
                        {% endfor %}
                    </li>
                </ul>
            </div>

            <div class="post-content-text">
                <div>本文:<br>{{ postcontent.text }}</div>
            </div>
        </div>

        
    </section>
    <div class="button-container">
        <!-- 削除&編集ボタン。投稿者のみが操作できるようにする -->
        {% if request.user == postcontent.author %} 
        <a href="{% url 'app:bosyuu_edit' postcontent.id %}">
            <button class="button-edit">編集</button>
        </a>
        
        <form  method="post" action="{% url 'app:bosyuu_delete' postcontent.id %}">
            {% csrf_token %}
            <button class="button-delete" type="submit" onclick='return confirm("本当に削除しますか？");' >削除</button>
        </form>
        {% endif %}
        <!-- この記事の投稿者が自分で「ない」場合のみ、チャットルームへのリンクを表示 -->
        {% if request.user != postcontent.author %} 
        <a href="{% url 'chat:room' name1 name2 %}">
            <button>{{ postcontent.author }}とチャット</button>
        </a>
        {% endif %}
    </div>
{% endblock %}

app/templates/app/bosyuu_edit.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="post-container">
    <ol class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><small>トップページ</small></a></li>
        <li><a href="{% url 'app:mypage' %}"><small>マイページ</small></a></li>
        <li><small>記事の編集</small></li>
    </ol>
    <h2>記事の編集</h2>
    <div class="post-tabpanel-container">
        {% include "app/bosyuu-article.html" %}
        <div id="kanyuu">

        </div>
        <div>
            <a href="{% url 'app:bosyuu_detail' postcontent.id %}"></a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/createpost.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="post-container">
    <ol class="breadcrumb">
        <li><a href="{% url 'app:index' %}"><small>トップページ</small></a></li>
        <li><a href="{% url 'app:mypage' %}"><small>マイページ</small></a></li>
        <li><small>新規作成</small></li>
    </ol>
    <h2>記事の新規作成</h2>
    <div class="create-post-container">
        <div class="bosyuu"><!-- TODO　できればここを部品化する -->
            {% include "app/bosyuu-article.html" %}
        </div>
        <div class="kanyuu">

        </div>
    </div>
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

    <h2>トップページ</h2>
    {% for postcontent in postcontents %}
    {% include "app/post-overview.html" %}
    {% endfor %}

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}
<div class="main-container-contents-login">
    <h2>ログイン</h2>
    <form class="form-signin" method="post">{% csrf_token %}
        {% if form.errors %}
            <p>ユーザー名かパスワードが間違っています</p>
        {% endif %}
        <label>ユーザー名</label><br>

        <input name="username">
        <br>
        <label>パスワード</label>
        <br>
        <input type="password" name="password"><br>

        <!-- <input type="submit" value="ログイン"><br> -->
        <button type="submit">ログイン</button><br>

        <!-- <p>もしくは</p>

        <a href="{% url 'social:begin' 'twitter' %}">
            <div class="twitter-api">
                twitterでログイン
            </div>
        </a>
        <a href="">
            <div class="facebook-api">
                <span>facebookでログイン</span>
            </div>
        </a>
        <a href="">
            <div class="google-api">
                <span>Googleでログイン</span>
            </div>
        </a> -->
        
        

        <p>初めましての方はこちらから</p>

        <button><a href="{% url 'app:signup' %}">新規会員登録</a></button>

    </form>
</div>
{% endblock %}

app/templates/app/mypage.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<ol class="breadcrumb"><!-- パンクズリスト -->
    <li><a href="{% url 'app:index' %}"><small>トップページ</small></a></li>
    <li><small>マイページ</small></li>
</ol>
<div class="main-container-contents-mypage">
    <h2>マイページ</h2>
    *こんにちは、{{ user.username }}さん！ここはあなた専用のページです*
        <button class="">
            <a href="{% url 'chat:index' %}">チャット相手一覧</a>
        </button>
    
        <button class="button-createpost">
            <a href="{% url 'app:createpost' %}">記事を新規作成する</a>
        </button>

    <h4>記事を管理する</h4>
    {% for mypost in myposts %}
    <div class="mypage-post">
        <div class="mypage-post-title">
            <a href="{% url 'app:bosyuu_detail' mypost.id %}">{{ mypost.title}}</a>
        </div>
        <div class="button-container"><!-- 削除&編集ボタン -->
            <a href="{% url 'app:bosyuu_edit' mypost.id %}">
                <button class="button-edit">編集</button>
            </a>
            <form  method="post" action="{% url 'app:bosyuu_delete' mypost.id %}">
                {% csrf_token %}
                <button class="button-delete" type="submit" onclick='return confirm("本当に削除しますか？");' >削除</button>
            </form>
        </div>
    </div>
    {% endfor %}
    
</div>
{% endblock %}

app/templates/app/post-overview.html
<section class="post">
    
    <div class="post-body">
        <div class="post-header">
            <div class="post-title">    
                <a href="{% url 'app:bosyuu_detail'　postcontent_id=postcontent.id %}"> <!--  bosyuu_detailの中身は後に正しい内容に変更する。その際、記事の主キーを渡すようにこのhrefも変更する。-->
                    <h3>{{ postcontent.title }}</h3>
                </a>
            </div>
            <div class="post-meta">
                （{{ postcontent.author }}/投稿日時：{{ postcontent.post_date }}）
            </div>
        </div>
        <div class="post-contents">
            <div class="post-content-sound">
                <audio controls><source src="{{ postcontent.sound.url }}" type="audio/mp3" /></audio>
            </div>
            <div class="post-content-issues">
                <ul>
                    <li>担当パート:
                        {% for mypart in postcontent.mypart.all %}
                            {{ mypart }},
                        {% endfor %}
                    </li>
                    <li>募集パート:
                        {% for recruite_part in postcontent.recruite_part.all %}
                            {{ recruite_part }},
                        {% endfor %}
                    </li>
                    <li>活動地域:
                        {% for active_area in postcontent.active_area.all %}
                            {{ active_area }},
                        {% endfor %}
                    </li>
                    <li>影響:
                        {{ postcontent.favorite }}
                    </li>
                    <li>ジャンル:
                        {% for genre in postcontent.genre.all %}
                            {{ genre }},
                        {% endfor %}
                    </li>
                    <li>
                        曜日:
                        {% for days_of_theweek in postcontent.days_of_theweek.all %}
                        {{ days_of_theweek }}
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

app/templates/app/postformcontent.html
{% extends 'app/createpost.html' %}

{% block content2 %}
<div>
    これは「postformcontent」というブロックから呼び出された領域です。
</div>

{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}
<div class="main-container-contents-login">
    <h2>新規登録</h2>
    <form action="{% url 'app:signup' %}" class="form-signin" method="post">{% csrf_token %}
        {% if form.errors %}
            <p>ユーザー名かパスワードが間違っています</p>
        {% endif %}
        <label>ユーザー名</label><br>
        {{ form.username }}
        {{ form.username.errors }}
        <br>
        <label>パスワード</label>
        <br>
        {{ form.password1 }}
        {{ form.password1.errors }}
        <br>
        <label>パスワード(確認)</label>
        <br>
        {{ form.password2 }}
        {{ form.password2.errors }}
        <br>
        <!-- <a href="{% url 'social:begin' 'twitter' %}">
            <div class="twitter-api">
                <span>twitterで新規登録</span>
            </div>
        </a>
        <div class="facebook-api">
            <span>facebookで新規登録</span>
        </div>
        <div class="google-api">
            <span>Googleで新規登録</span>
        </div> -->
        
        <!-- <input type="submit" value="新規登録する"> -->
        <button type="submit">新規登録する</button>

    </form>
</div>
{% endblock %}